import secrets

LDAPS_SERVEUR = secrets.LDAPS_SERVEUR
SVC_USER = secrets.SVC_USER
SVC_PASSWORD = secrets.SVC_PASSWORD
PRIVATE_KEY = secrets.PRIVATE_KEY
CERT = secrets.CERT
ROOT_CA = secrets.ROOT_CA
LDAPS_PORT = secrets.LDAPS_PORT
